services:

  #oracle:
  #  image: container-registry.oracle.com/database/free:latest
  #  container_name: genorc
  #  ports:
  #    - "1521:1521"
  #  networks:
  #    - genai-network
  #  environment:
  #    ORACLE_PWD: "genorc"
  #  volumes:
  #    - ./oracle_scripts:/opt/oracle/scripts/setup

  postgres:
    image: 'postgres:16.8'
    container_name: 'gendb'
    ports:
      - '5432:5432'
    networks:
      - genai-network
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: genai
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: 'genkc'
    ports:
      - '11080:8080'
    networks:
      - genai-network
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: kcadmin
      KEYCLOAK_ADMIN_PASSWORD: kcadmin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://gendb:5432/genai
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    healthcheck:
      test: ["CMD", "curl", "-f", "http://genkc:9090/health/ready"]
    volumes:
      - ./kcdata:/opt/keycloak/data
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --verbose


networks:
  genai-network:
    driver: bridge
